import { type ReactNode, useEffect, useState } from "react";
import type { CalendarDate } from "@internationalized/date";
import { AlertCircle, CheckCircle, Circle, CurrencyDollar, FilePlus02, InfoCircle, SearchLg, XClose } from "@untitledui/icons";
import { Button } from "@/components/base/buttons/button";
import { Input } from "@/components/base/input/input";
import { RadioButton, RadioGroup } from "@/components/base/radio-buttons/radio-buttons";
import { Select } from "@/components/base/select/select";
import { END_OF_DAY, START_OF_DAY } from "@/pages/deal-activation-system/dates";
import { DateTimePicker } from "@/pages/deal-activation-system/round-1-components/datetime-picker";
import { cx } from "@/utils/cx";
import { currentFillMode, useRegisterPageFill } from "../../../shared/demo-fill";
import { Fillable } from "../../../shared/demo-fill-ui";
import type { AuctionRule } from "./das-data";
import { DasShell, JumpLink, NewFieldBadge, PINK, PinkAction, Section, TEAL } from "./das-shell";
import { AdUnitTypeField, DeviceLanguageField, ExistingTargets, KeywordChipInput, MatchLogicField } from "./keyword-targeting";
import {
    type Issue,
    SECTIONS,
    type SectionId,
    type SetupForm,
    type SetupPreset,
    allPresets,
    deals,
    fill,
    fillAll,
    flightDays,
    library,
    rules,
    spoilAll,
    started,
    TODAY,
    validate,
} from "./setup-data";
import { stepHref, useSetupDraft } from "./setup-store";

/**
 * Deal Activation System → Campaign Setup, one page.
 *
 * Kickoff feedback: "make it a one-pager instead of step-by-step." The five wizard
 * steps (General → Budget → Targeting → Creative → Review) become sections on one
 * scrolling form. Review isn't a page any more: a sticky summary rail tracks what's
 * left, and Publish validates on press — every problem is flagged in place, in the
 * "On this page" rail and in a banner that links to each one.
 *
 * Demo fill: every empty text field is clickable and populates itself, and the toolbar
 * fills the whole page. The walkthrough strip at the top carries the draft from one step
 * to the next. Both are prototype chrome — see prototypes/shared/demo-fill.ts.
 */

export type FieldError = (field: string) => string | undefined;
export type Setter = (p: Partial<SetupForm>) => void;

/* ------------------------------------------------------------ Sections --- */

const FieldMessage = ({ children }: { children: ReactNode }) => (
    <p className="flex items-center gap-2 text-sm font-medium text-error-primary">
        <AlertCircle className="size-4 shrink-0" aria-hidden="true" /> {children}
    </p>
);

/**
 * `extended` turns on the fields the real product has that Round 1 never modelled.
 * Round 1 leaves it off so it stays the form that was reviewed on 22 Sep.
 */
export const DealSection = ({ form, set, error, extended }: { form: SetupForm; set: Setter; error: FieldError; extended?: boolean }) => {
    const [mode, setMode] = useState("existing");
    return (
        <Section id="deal" title="General" description="Campaigns nest under a deal. Budgets belong to the campaign, not the deal.">
            <RadioGroup size="sm" value={mode} onChange={setMode} className="gap-4" aria-label="Deal">
                <RadioButton value="generate" label="New deal, generate ID" />
                <RadioButton value="create" label="New deal, custom ID" />
                <div className="flex flex-col gap-3 lg:flex-row lg:items-start">
                    <RadioButton value="existing" label="Add to existing deal" className="lg:mt-2.5 lg:w-52" />
                    <div className="flex-1">
                        <Fillable filled={Boolean(form.dealId)} onFill={() => set({ dealId: fill.dealId() })}>
                            <Select
                                aria-label="Existing deal"
                                placeholder="Choose a deal"
                                items={deals}
                                selectedKey={form.dealId ?? null}
                                onSelectionChange={(k) => set({ dealId: k ? String(k) : undefined })}
                                isDisabled={mode !== "existing"}
                                isInvalid={Boolean(error("deal"))}
                                hint={error("deal")}
                            >
                                {(item) => (
                                    <Select.Item id={item.id} supportingText={item.supportingText}>
                                        {item.label}
                                    </Select.Item>
                                )}
                            </Select>
                        </Fillable>
                    </div>
                </div>
            </RadioGroup>
            {extended && form.dealId && (
                <Input label="Deal ID" size="md" value={form.dealId} isDisabled hint="Generated by Nimbus when the deal is created." wrapperClassName="max-w-xs" />
            )}
            <Fillable filled={Boolean(form.name)} onFill={() => set({ name: fill.name() })}>
                <Input
                    label="Campaign Name"
                    size="md"
                    placeholder="e.g. Sports fans · Interstitial"
                    value={form.name}
                    onChange={(name) => set({ name })}
                    isRequired
                    isInvalid={Boolean(error("name"))}
                    hint={error("name")}
                />
            </Fillable>
        </Section>
    );
};

export const RulesSection = ({ form, set, error }: { form: SetupForm; set: Setter; error: FieldError }) => (
    <Section id="rules" title="Auction Rules" description="How this campaign competes with open-marketplace auctions.">
        <RadioGroup
            size="sm"
            value={form.rule ?? null}
            onChange={(v) => set({ rule: v as AuctionRule })}
            className="grid grid-cols-1 gap-3 md:grid-cols-2"
            aria-label="Auction rule"
        >
            {rules.map((r) => (
                <div
                    key={r.id}
                    className={cx("rounded-xl p-4 ring-1", form.rule === r.id ? "" : error("rule") ? "ring-error_subtle" : "ring-secondary")}
                    style={form.rule === r.id ? { boxShadow: `inset 0 0 0 2px ${TEAL}`, backgroundColor: `${TEAL}0a` } : undefined}
                >
                    <RadioButton value={r.id} label={r.id} hint={r.hint} />
                </div>
            ))}
        </RadioGroup>
        {error("rule") && <FieldMessage>{error("rule")}</FieldMessage>}
        <Select
            label="Priority"
            items={[
                { id: "even", label: "Even distribution (default)" },
                { id: "1", label: "1 — highest" },
                { id: "2", label: "2" },
                { id: "3", label: "3" },
            ]}
            defaultSelectedKey="even"
            className="max-w-xs"
        >
            {(item) => <Select.Item id={item.id}>{item.label}</Select.Item>}
        </Select>
    </Section>
);

/** Start and end as date & time pickers (bold date, muted time), in UTC. */
const FlightDates = ({ form, set, error, calendarOpen }: { form: SetupForm; set: Setter; error: FieldError; calendarOpen?: boolean }) => {
    const days = flightDays(form);
    const field = (which: "start" | "end") => {
        const err = error(which);
        const isStart = which === "start";
        return (
            <div className="flex flex-col gap-1.5">
                <span className="text-sm font-medium text-secondary">
                    {isStart ? "Start" : "End"} <span className="text-brand-tertiary">*</span>
                </span>
                <Fillable
                    filled={Boolean(form[which])}
                    onFill={() => set(isStart ? { start: fill.start() } : { end: fill.end() })}
                    hint={isStart ? "Click to fill" : "Click to fill"}
                >
                    <DateTimePicker
                        label={isStart ? "Start" : "End"}
                        value={{ date: form[which], time: (isStart ? form.startTime : form.endTime) ?? (isStart ? START_OF_DAY : END_OF_DAY) }}
                        onChange={(v) => set(isStart ? { start: v.date, startTime: v.time } : { end: v.date, endTime: v.time })}
                        minValue={isStart ? TODAY : (form.start ?? TODAY)}
                        today={TODAY}
                        notBefore={!isStart && form.start ? { date: form.start, time: form.startTime ?? START_OF_DAY } : undefined}
                        invalid={Boolean(err)}
                        defaultOpen={calendarOpen && isStart}
                        placeholder={isStart ? "Select start" : "Select end"}
                    />
                </Fillable>
                {err && <span className="text-sm text-error-primary">{err}</span>}
            </div>
        );
    };
    return (
        <div className="flex flex-col gap-3">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:gap-4">
                {field("start")}
                <span className="hidden pt-9 text-quaternary sm:block">→</span>
                {field("end")}
                {days && <span className="text-sm text-tertiary sm:pt-9">{days}-day flight</span>}
            </div>
            <p className="text-sm text-tertiary italic">All scheduling times are in UTC. Past dates can't be picked.</p>
        </div>
    );
};

export const BudgetSection = ({ form, set, error, calendarOpen, extended }: { form: SetupForm; set: Setter; error: FieldError; calendarOpen?: boolean; extended?: boolean }) => {
    const flight = <FlightDates form={form} set={set} error={error} calendarOpen={calendarOpen} />;
    if (form.rule === "Fallback") {
        return (
            <Section id="budget" title="Budget">
                <p className="flex items-center gap-2 text-sm text-tertiary">
                    <InfoCircle className="size-4" aria-hidden="true" /> Fallback campaigns have no budget or eCPM. Set the flight dates only.
                </p>
                {flight}
            </Section>
        );
    }
    return (
        <Section id="budget" title="Budget" description="Pacing is front-loaded hourly: up to 1/24th of the daily budget spends at the start of each hour.">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                <Fillable filled={Boolean(form.budget)} onFill={() => set({ budget: fill.budget() })}>
                    <Input
                        label="Budget"
                        size="md"
                        icon={CurrencyDollar}
                        placeholder="0.00"
                        value={form.budget}
                        onChange={(budget) => set({ budget })}
                        isRequired
                        isInvalid={Boolean(error("budget"))}
                        hint={error("budget")}
                    />
                </Fillable>
                <Fillable filled={Boolean(form.ecpm)} onFill={() => set({ ecpm: fill.ecpm() })}>
                    <Input
                        label="Bid Amount (eCPM)"
                        size="md"
                        icon={CurrencyDollar}
                        placeholder="0.00"
                        value={form.ecpm}
                        onChange={(ecpm) => set({ ecpm })}
                        isRequired
                        isInvalid={Boolean(error("ecpm"))}
                        hint={error("ecpm") ?? "Selling value, not a floor."}
                    />
                </Fillable>
                <Input label="Daily Impression Cap" size="md" placeholder="No cap" hint="Optional" />
                {extended && (
                    <Select
                        label="Frequency Cap"
                        items={[
                            { id: "disabled", label: "Disabled" },
                            { id: "1h", label: "1 per hour" },
                            { id: "3d", label: "3 per day" },
                            { id: "5d", label: "5 per day" },
                        ]}
                        defaultSelectedKey="disabled"
                    >
                        {(item) => <Select.Item id={item.id}>{item.label}</Select.Item>}
                    </Select>
                )}
            </div>
            {flight}
        </Section>
    );
};

/**
 * One module per thing you can target on, all at the same level.
 *
 * Previously Geos / Platform / Apps were loose rows while Keywords and "Standard targets"
 * were cards, which made them read as different tiers. They aren't. "Standard targets"
 * was our invention and is gone; Device language and Match logic are gone too — neither
 * is in the charter, and matching is exact.
 */
const TargetModule = ({ title, added, children }: { title: string; added?: boolean; children: ReactNode }) => (
    <div className="flex flex-col gap-4 rounded-xl p-5 ring-1 ring-secondary">
        <div className="flex items-center gap-2">
            <h3 className="text-lg font-semibold text-primary">{title}</h3>
            {added && <NewFieldBadge />}
        </div>
        {children}
    </div>
);

/**
 * Round 1 targeting — as built to the Extended Targeting charter and reviewed on 22 Sep.
 *
 * Match Logic and Device Language are deliberately still here. Both were dropped for
 * Round 2 on the 1 Oct instruction, but Match Logic is specified in the charter (with a
 * wireframe), so Round 1 keeps them as the record of what that document asked for.
 * Round 2's version lives in prototypes/das/v2/screens/targeting-section.tsx.
 */
export const TargetingSection = ({ form, set, empty }: { form: SetupForm; set: Setter; empty: boolean }) => (
    <Section id="targeting" title="Targeting" description="Leave a target empty to include everyone.">
        <div className="flex flex-col gap-4">
            <ExistingTargets empty={empty} />
            <TargetModule title="Ad Unit">
                <AdUnitTypeField value={form.adUnits} onChange={(adUnits) => set({ adUnits })} />
            </TargetModule>
            <TargetModule title="Keywords" added>
                <Fillable filled={form.keywords.length > 0} onFill={() => set({ keywords: fill.keywords() })}>
                    <KeywordChipInput value={form.keywords} onChange={(keywords) => set({ keywords })} />
                </Fillable>
                <MatchLogicField value={form.match} onChange={(match) => set({ match })} count={form.keywords.length} />
            </TargetModule>
            <TargetModule title="Device Language">
                <DeviceLanguageField value={form.languages} onChange={(languages) => set({ languages })} />
            </TargetModule>
        </div>
    </Section>
);

/**
 * `onUploadNew` is what makes "Upload new asset" leave for the asset library and come
 * back with the creative attached. Round 1 has no asset library, so it leaves it unset
 * and the action stays inert, exactly as it was reviewed.
 */
export const CreativeSection = ({ form, set, error, onUploadNew, extended }: { form: SetupForm; set: Setter; error: FieldError; onUploadNew?: () => void; extended?: boolean }) => {
    const rows = form.creatives;
    const mixed = new Set(rows.map((c) => c.type)).size > 1;
    const next = library.find((c) => !rows.includes(c) && c.type === "HTML");
    const err = error("creatives");
    return (
        <Section
            id="creative"
            title="Creative"
            description="Add creatives from your asset library. A campaign can hold many creatives, all of the same type. For another format or language, use Publish & Duplicate."
            trailing={<PinkAction onPress={onUploadNew}>Upload new asset</PinkAction>}
        >
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
                <Input aria-label="Search assets" size="md" icon={SearchLg} placeholder="Search assets" wrapperClassName="flex-1" />
                <Button color="primary-pink" className="uppercase" isDisabled={!next} onClick={() => next && set({ creatives: [...rows, next] })}>
                    Add
                </Button>
            </div>
            {rows.length === 0 ? (
                <Fillable filled={false} onFill={() => set({ creatives: fill.creatives() })} hint="Click to add creatives">
                    <div
                        className={cx(
                            "flex flex-col items-center gap-2 rounded-xl border border-dashed px-6 py-8 text-center",
                            err ? "border-error_subtle" : "border-secondary",
                        )}
                        style={err ? { backgroundColor: `${PINK}0a` } : undefined}
                    >
                        <FilePlus02 className="size-6 text-fg-quaternary" aria-hidden="true" />
                        <p className="text-sm font-semibold text-primary">No creatives yet</p>
                        <p className="max-w-sm text-sm text-tertiary">
                            Search your asset library above, or upload a new asset. HTML and VAST can't be mixed in one campaign.
                        </p>
                    </div>
                </Fillable>
            ) : (
                <div className="overflow-hidden rounded-xl ring-1 ring-secondary">
                    {rows.map((c, i) => {
                        const bad = mixed && c.type === "VAST (xml)";
                        return (
                            <div
                                key={c.name}
                                className={cx(
                                    "flex items-center gap-4 border-b border-secondary px-4 py-3 last:border-b-0",
                                    i % 2 === 1 && "bg-secondary/40",
                                    bad && "bg-error-primary",
                                )}
                            >
                                <span className="min-w-0 flex-1 truncate text-sm font-medium text-secondary">{c.name}</span>
                                <span className={cx("w-20 text-sm", bad ? "font-semibold text-error-primary" : "text-tertiary")}>{c.type}</span>
                                <span className="hidden w-28 text-sm text-tertiary sm:block">{c.size}</span>
                                {extended && <span className="hidden w-32 text-sm text-tertiary lg:block">No cap</span>}
                                <PinkAction icon={XClose} onPress={() => set({ creatives: rows.filter((x) => x !== c) })}>
                                    Remove
                                </PinkAction>
                            </div>
                        );
                    })}
                </div>
            )}
            {err && <FieldMessage>{err === "Creatives mix HTML and VAST (xml)" ? "Mixed creative types. Remove the VAST creative, or publish it as a duplicate campaign." : err}</FieldMessage>}
            <details className="rounded-xl bg-secondary/50 px-4 py-3 text-sm text-secondary">
                <summary className="cursor-pointer font-semibold text-primary">Creative requirements</summary>
                <ul className="mt-2 list-disc space-y-1 pl-5">
                    <li>HTML (static): 320×50 banner, 300×250 medium rectangle, 320×480 full screen.</li>
                    <li>VAST (video): raw, unwrapped VAST XML. No tags or URLs.</li>
                    <li>No macros in creatives or third-party trackers. 300×600, 620×250 and 970×250 may render full screen.</li>
                </ul>
            </details>
        </Section>
    );
};

/* ---------------------------------------------------------- Summary rail --- */

const SummaryRow = ({ label, children }: { label: string; children: ReactNode }) => (
    <div className="flex items-start justify-between gap-3 py-2 text-sm">
        <span className="shrink-0 text-tertiary">{label}</span>
        <span className="text-right font-medium text-primary">{children}</span>
    </div>
);

const Missing = () => <span className="text-quaternary">—</span>;

const fmtDate = (c?: CalendarDate) =>
    c ? new Date(Date.UTC(c.year, c.month - 1, c.day)).toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" }) : undefined;

export interface ProgressProps {
    form: SetupForm;
    issues: Issue[];
    attempted: boolean;
}

const sectionState = ({ form, issues, attempted }: ProgressProps, s: SectionId) => {
    const bad = issues.some((x) => x.section === s);
    const blank = SECTIONS.every((x) => !started(form, x.id));
    const isStarted = started(form, s) || (s === "targeting" && !blank && form.creatives.length > 0);
    return bad && attempted ? "error" : bad || !isStarted ? "todo" : "done";
};

export const SummaryRail = (props: ProgressProps & { onPublish: () => void }) => {
    const { form, issues, attempted, onPublish } = props;
    const blank = SECTIONS.every((s) => !started(form, s.id));
    const done = SECTIONS.filter((s) => sectionState(props, s.id) === "done").length;
    const deal = deals.find((x) => x.id === form.dealId);
    const keywordCount = form.keywords.length;

    return (
        <aside className="flex flex-col gap-5 rounded-2xl bg-primary p-5 shadow-sm ring-1 ring-secondary xl:sticky xl:top-14">
            <div className="flex flex-col gap-2">
                <div className="flex items-center justify-between">
                    <h2 className="text-lg font-semibold text-primary">{blank ? "Campaign summary" : "Ready to publish?"}</h2>
                    <span className="text-sm font-semibold" style={{ color: issues.length ? PINK : TEAL }}>
                        {done}/{SECTIONS.length}
                    </span>
                </div>
                <div className="flex gap-1">
                    {SECTIONS.map((s) => {
                        const st = sectionState(props, s.id);
                        return (
                            <span
                                key={s.id}
                                className="h-1.5 flex-1 rounded-full"
                                style={{ backgroundColor: st === "error" ? PINK : st === "done" ? TEAL : "#EAECF0" }}
                                title={s.title}
                            />
                        );
                    })}
                </div>
            </div>

            {blank && !attempted ? (
                <div className="flex flex-col gap-2 rounded-xl border border-dashed border-secondary p-4 text-sm">
                    <p className="font-semibold text-primary">Your summary builds here</p>
                    <p className="text-tertiary">As you fill in the form, each choice shows up below and the checklist tells you what's left. Start with the deal.</p>
                    <JumpLink to="deal" className="font-semibold" style={{ color: PINK }}>
                        Start with General →
                    </JumpLink>
                </div>
            ) : issues.length > 0 ? (
                <div className="flex flex-col gap-2">
                    <span className="text-xs font-semibold text-tertiary uppercase">{attempted ? "Fix before publishing" : `${issues.length} left to finish`}</span>
                    <ul className="flex flex-col gap-1.5">
                        {issues.map((issue) => (
                            <li key={issue.field + issue.text}>
                                <JumpLink
                                    to={issue.section}
                                    className={cx(
                                        "flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition-colors",
                                        attempted ? "text-error-primary" : "bg-secondary/60 text-secondary hover:bg-primary_hover",
                                    )}
                                    style={attempted ? { backgroundColor: `${PINK}14` } : undefined}
                                >
                                    {attempted ? (
                                        <AlertCircle className="size-4 shrink-0" aria-hidden="true" />
                                    ) : (
                                        <Circle className="size-4 shrink-0 text-fg-quaternary" aria-hidden="true" />
                                    )}
                                    {issue.text}
                                </JumpLink>
                            </li>
                        ))}
                    </ul>
                </div>
            ) : (
                <p className="flex items-center gap-2 text-sm font-medium" style={{ color: TEAL }}>
                    <CheckCircle className="size-4" aria-hidden="true" /> Everything checks out.
                </p>
            )}

            <div className="divide-y divide-secondary border-y border-secondary">
                <SummaryRow label="Deal">{deal?.label ?? <Missing />}</SummaryRow>
                <SummaryRow label="Rule">{form.rule ?? <Missing />}</SummaryRow>
                {form.rule !== "Fallback" && (
                    <SummaryRow label="Budget · eCPM">
                        {form.budget ? `$${form.budget.replace(/\.00$/, "")}` : <Missing />} · {form.ecpm ? `$${form.ecpm}` : <Missing />}
                    </SummaryRow>
                )}
                {form.rule && form.rule !== "Fallback" && form.budget && form.ecpm && flightDays(form) && (
                    <SummaryRow label="Est. delivery">≈ 2.9M impressions · $806/day</SummaryRow>
                )}
                <SummaryRow label="Flight">{form.start || form.end ? `${fmtDate(form.start) ?? "?"} – ${fmtDate(form.end) ?? "?"} (UTC)` : <Missing />}</SummaryRow>
                <SummaryRow label="Keywords">
                    {keywordCount ? `${keywordCount} keyword${keywordCount === 1 ? "" : "s"}` : <span className="text-tertiary">Not Specified</span>}
                </SummaryRow>
                <SummaryRow label="Creatives">
                    {form.creatives.length ? `${form.creatives.length} × ${[...new Set(form.creatives.map((c) => c.type))].join(" + ")}` : <Missing />}
                </SummaryRow>
            </div>

            <div className="flex flex-col gap-2">
                <Button color="primary-pink" className="uppercase" onClick={onPublish}>
                    Publish
                </Button>
                <Button color="secondary" className="uppercase" onClick={onPublish}>
                    Publish &amp; duplicate
                </Button>
                <Button color="link-gray" size="sm">
                    Save draft
                </Button>
            </div>
            <p className="text-xs text-tertiary">Publish checks everything first. Anything missing is flagged on the page, and nothing goes live until it's fixed.</p>
        </aside>
    );
};

/* ------------------------------------------------------------ Section nav --- */

const SectionNav = ({ current, ...props }: ProgressProps & { current?: SectionId }) => {
    const { form, issues, attempted } = props;
    const blank = SECTIONS.every((s) => !started(form, s.id));
    return (
        <nav aria-label="Form sections" className="hidden flex-col gap-1 xl:sticky xl:top-14 xl:flex xl:self-start">
            <span className="mb-2 px-3 text-xs font-semibold text-tertiary uppercase">On this page</span>
            {SECTIONS.map((s, i) => {
                const state = sectionState(props, s.id);
                const count = issues.filter((x) => x.section === s.id).length;
                return (
                    <JumpLink
                        key={s.id}
                        to={s.id}
                        className={cx(
                            "flex items-start gap-2.5 rounded-lg px-3 py-2 text-sm font-medium transition-colors hover:bg-primary_hover",
                            s.id === current && "bg-secondary",
                            state === "error" ? "text-error-primary" : state === "done" ? "text-primary" : "text-tertiary",
                        )}
                    >
                        {state === "error" ? (
                            <AlertCircle className="mt-0.5 size-4 shrink-0 text-fg-error-secondary" aria-hidden="true" />
                        ) : state === "done" ? (
                            <CheckCircle className="mt-0.5 size-4 shrink-0" style={{ color: TEAL }} aria-hidden="true" />
                        ) : (
                            <span
                                className="mt-0.5 flex size-4 shrink-0 items-center justify-center rounded-full border-[1.5px] border-dashed border-fg-quaternary text-[9px] font-bold text-quaternary"
                                aria-hidden="true"
                            >
                                {i + 1}
                            </span>
                        )}
                        <span className="flex flex-col">
                            {s.title}
                            {state === "error" && <span className="text-xs font-normal">{count} to fix</span>}
                            {s.id === "targeting" && state === "todo" && <span className="text-xs font-normal">Optional</span>}
                        </span>
                    </JumpLink>
                );
            })}
            {blank && !attempted && <p className="mt-3 rounded-lg bg-secondary px-3 py-2.5 text-xs text-tertiary">Nothing filled in yet. Sections tick off as you complete them.</p>}
        </nav>
    );
};

/* ------------------------------------------------------ Walkthrough strip --- */

/**
 * Prototype chrome, not product UI. The screens below are one page in the product; this
 * strip is how a demo steps through the states of it while keeping what was filled in.
 */
const WALKTHROUGH: { id: string; label: string }[] = [
    { id: "setup-empty", label: "Empty" },
    { id: "step-deal", label: "Deal" },
    { id: "step-rules", label: "Rules" },
    { id: "step-budget", label: "Budget" },
    { id: "step-targeting", label: "Targeting" },
    { id: "step-creative", label: "Creative" },
    { id: "setup-ready", label: "Ready" },
];

const WalkthroughStrip = ({ screenId }: { screenId?: string }) => {
    const i = WALKTHROUGH.findIndex((s) => s.id === screenId);
    if (i < 0) return null;
    const prev = WALKTHROUGH[i - 1];
    const next = WALKTHROUGH[i + 1];
    return (
        <div className="flex flex-wrap items-center gap-x-3 gap-y-2 rounded-xl border border-dashed px-4 py-2.5" style={{ borderColor: `${PINK}66`, backgroundColor: `${PINK}08` }}>
            <span className="text-xs font-bold tracking-wide uppercase" style={{ color: PINK }}>
                Walkthrough
            </span>
            <ol className="flex flex-wrap items-center gap-1">
                {WALKTHROUGH.map((s, j) => (
                    <li key={s.id}>
                        <a
                            href={stepHref(s.id)}
                            className={cx("rounded-md px-2 py-1 text-xs font-semibold transition-colors", j === i ? "text-white" : "text-tertiary hover:bg-primary")}
                            style={j === i ? { backgroundColor: PINK } : undefined}
                        >
                            {j + 1}. {s.label}
                        </a>
                    </li>
                ))}
            </ol>
            <div className="ml-auto flex items-center gap-2">
                {prev && (
                    <a href={stepHref(prev.id)} className="rounded-md px-2.5 py-1 text-xs font-semibold text-secondary ring-1 ring-secondary hover:bg-primary">
                        ← {prev.label}
                    </a>
                )}
                {next && (
                    <a href={stepHref(next.id)} className="rounded-md px-2.5 py-1 text-xs font-semibold text-white" style={{ backgroundColor: PINK }}>
                        {next.label} →
                    </a>
                )}
            </div>
            <p className="w-full text-xs text-tertiary">
                Keeps what you've filled in. The toolbar screen picker and the index start each screen fresh instead.
            </p>
        </div>
    );
};

/* ------------------------------------------------------------------ Page --- */

export interface CampaignSetupOnePageProps {
    preset?: SetupPreset;
    /** Publish has been pressed: show every error in place. */
    attempted?: boolean;
    /** The flight-date range picker is open on load. */
    calendarOpen?: boolean;
    /** Section to scroll to and mark as current on load (step-by-step walkthrough). */
    focus?: SectionId;
    /** Screen id, so the walkthrough strip knows where it is. */
    screenId?: string;
}

export const CampaignSetupOnePage = ({ preset = "ready", attempted: initialAttempted = false, calendarOpen, focus, screenId }: CampaignSetupOnePageProps) => {
    const { form, update } = useSetupDraft(allPresets[preset]);
    const [attempted, setAttempted] = useState(initialAttempted);
    const set: Setter = (p) => update(p);
    const issues = validate(form);
    const error: FieldError = (field) => (attempted ? issues.find((i) => i.field === field)?.text : undefined);
    const progress = { form, issues, attempted };

    // The toolbar's "Fill page". In bad mode it also presses Publish for you, so the
    // error states appear immediately rather than waiting for a second click.
    useRegisterPageFill(() => {
        const bad = currentFillMode() === "bad";
        update(bad ? spoilAll(form) : fillAll(form));
        if (bad) setAttempted(true);
    });

    // Deep link to an open calendar: bring the flight dates into view first.
    useEffect(() => {
        if (calendarOpen) document.getElementById("budget")?.scrollIntoView({ block: "center" });
        else if (focus) document.getElementById(focus)?.scrollIntoView({ block: "start" });
    }, [calendarOpen, focus]);

    const publish = () => {
        if (issues.length) {
            setAttempted(true);
            window.scrollTo({ top: 0, behavior: "smooth" });
        } else {
            window.location.hash = "#/setup-published";
        }
    };

    return (
        <DasShell
            navKey="deal activation setup"
            tabs={[
                { label: "Create Campaign", active: true, href: "#/setup-empty" },
                { label: "View Campaigns", href: "#/campaigns" },
            ]}
            concept={{
                label: "Concept A",
                title: "One-page setup with a live summary rail",
                notes: [
                    "The five wizard steps become five sections on one page. The left rail jumps between them and shows what's done, what's left and, after Publish, what's wrong.",
                    "Publish is never greyed out. Pressing it checks everything: problems are flagged on the fields, in the rail and in a banner that links to each one.",
                    "Start and end use date & time pickers: pick the day on the calendar and the UTC time underneath. Past dates can't be picked, and an end before the start is caught. Budget and eCPM hide for Fallback campaigns.",
                ],
            }}
        >
            <div className="grid grid-cols-1 gap-8 px-8 py-8 xl:grid-cols-[190px_minmax(0,1fr)_340px]">
                <SectionNav {...progress} current={focus} />
                <div className="flex min-w-0 flex-col gap-6">
                    <WalkthroughStrip screenId={screenId} />
                    <div>
                        {attempted && issues.length > 0 && (
                            <div role="alert" className="mb-6 flex flex-col gap-3 rounded-xl p-4 ring-1 ring-error_subtle" style={{ backgroundColor: `${PINK}0f` }}>
                                <p className="flex items-center gap-2 text-sm font-semibold text-error-primary">
                                    <AlertCircle className="size-5" aria-hidden="true" />
                                    Can't publish yet: {issues.length} {issues.length === 1 ? "thing needs" : "things need"} fixing
                                </p>
                                <ul className="flex flex-wrap gap-2">
                                    {issues.map((i) => (
                                        <li key={i.field + i.text}>
                                            <JumpLink
                                                to={i.section}
                                                className="inline-flex items-center gap-1 rounded-md bg-primary px-2.5 py-1 text-sm font-medium text-error-primary ring-1 ring-error_subtle"
                                            >
                                                {i.text} →
                                            </JumpLink>
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        )}
                        <DealSection form={form} set={set} error={error} />
                        <RulesSection form={form} set={set} error={error} />
                        <BudgetSection form={form} set={set} error={error} calendarOpen={calendarOpen} />
                        <TargetingSection form={form} set={set} empty={preset === "empty"} />
                        <CreativeSection form={form} set={set} error={error} />
                    </div>
                </div>
                <div>
                    <SummaryRail {...progress} onPublish={publish} />
                </div>
            </div>
        </DasShell>
    );
};

export default CampaignSetupOnePage;
